language: cpp
# compiler:
#   - gcc
cache: apt
# run on new infra
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

env:
  global:
    # required packages to install
    - RISCV="/home/travis/riscv_install"
    - PATH="$PATH:$RISCV/bin"
# git:
#       submodules: false # we'll do git submodule update ourselves
before_install:
  - pwd
  - mkdir -p $RISCV
  - echo $RISCV
  - echo $PATH
    # fix urls to be https to avoid pubkey issues
  # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # - git submodule update --init
    # hack to deal with sub-sub module git -> https url
  # - cd riscv-tests && sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules && git submodule update --init && cd ..
  # - cd riscv-llvm && sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules && git submodule update --init && cd ..
    # set jobs to 1 to avoid running out of memory on the travis machine
  - sed -i.bak 's/JOBS=16/JOBS=6/' build.common
  # need to build pk with riscv-gcc
  - sed -i.bak 's/build_project riscv-pk/CC=riscv64-unknown-elf-gcc CXX=riscv64-unknown-elf-g++ build_project riscv-pk/' build.sh
  # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  # - sudo apt-get update -qq
  # - sudo apt-get install -qq ${PKGS}
  # - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # - $CC --version
  # - ls /usr/bin/gcc*
  - export CXX="g++-4.8" CC="gcc-4.8"
  # - $CC --version
install: travis_wait
script:
  - cat build.sh
  - ./build.sh
  # - ls $RISCV
  # - ls $RISCV/bin
  # - ls $RISCV/riscv64-unknown-elf
  # - cd riscv-pk
  # - mkdir build
  # - cd build
  # - CC=riscv64-unknown-elf-gcc CXX=riscv64-unknown-elf-g++ ../configure --prefix=$RISCV/riscv64-unknown-elf --host=riscv64-unknown-elf
  # - ../configure --prefix=$RISCV/riscv64-unknown-elf --build=riscv64-unknown-elf
  # - cat config.log
  # - make
  # - make install
